// Copyright 2017-2026 @pezkuwi/api-contract authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as apiInfo } from '@pezkuwi/api/packageInfo';
import { packageInfo as typesInfo } from '@pezkuwi/types/packageInfo';
import { detectPackage } from '@pezkuwi/util';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [apiInfo, typesInfo]);
