// Copyright 2017-2026 @pezkuwi/types-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/types-augment', path: 'auto', type: 'auto', version: '16.5.4' };
