// Copyright 2017-2026 @pezkuwi/rpc-core authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as providerInfo } from '@pezkuwi/rpc-provider/packageInfo';
import { packageInfo as typesInfo } from '@pezkuwi/types/packageInfo';
import { detectPackage } from '@pezkuwi/util';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [providerInfo, typesInfo]);
