// Auto-generated via `yarn polkadot-types-from-defs`, do not edit
/* eslint-disable */

// import type lookup before we augment - in some environments
// this is required to allow for ambient/previous definitions
import '@pezkuwi/types/types/registry';

import type { AssetHubDicleRuntimeAhMigrationRcPalletsOrigin, AssetHubDicleRuntimeDynamicParamsIssuanceFalloff, AssetHubDicleRuntimeDynamicParamsIssuanceIdealStake, AssetHubDicleRuntimeDynamicParamsIssuanceMaxInflation, AssetHubDicleRuntimeDynamicParamsIssuanceMinInflation, AssetHubDicleRuntimeDynamicParamsIssuanceParameters, AssetHubDicleRuntimeDynamicParamsIssuanceParametersKey, AssetHubDicleRuntimeDynamicParamsIssuanceParametersValue, AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnIdleWeight, AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnInitWeight, AssetHubDicleRuntimeDynamicParamsMessageQueueParameters, AssetHubDicleRuntimeDynamicParamsMessageQueueParametersKey, AssetHubDicleRuntimeDynamicParamsMessageQueueParametersValue, AssetHubDicleRuntimeDynamicParamsSchedulerMaxScheduledPerBlock, AssetHubDicleRuntimeDynamicParamsSchedulerMaximumWeight, AssetHubDicleRuntimeDynamicParamsSchedulerParameters, AssetHubDicleRuntimeDynamicParamsSchedulerParametersKey, AssetHubDicleRuntimeDynamicParamsSchedulerParametersValue, AssetHubDicleRuntimeDynamicParamsStakingElectionMaxElectingVoters, AssetHubDicleRuntimeDynamicParamsStakingElectionMaxEraDuration, AssetHubDicleRuntimeDynamicParamsStakingElectionMaxSignedSubmissions, AssetHubDicleRuntimeDynamicParamsStakingElectionMinerPages, AssetHubDicleRuntimeDynamicParamsStakingElectionParameters, AssetHubDicleRuntimeDynamicParamsStakingElectionParametersKey, AssetHubDicleRuntimeDynamicParamsStakingElectionParametersValue, AssetHubDicleRuntimeDynamicParamsStakingElectionSignedPhase, AssetHubDicleRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock, AssetHubDicleRuntimeDynamicParamsStakingElectionUnsignedPhase, AssetHubDicleRuntimeDynamicParamsTreasuryBurnDestination, AssetHubDicleRuntimeDynamicParamsTreasuryBurnPortion, AssetHubDicleRuntimeDynamicParamsTreasuryParameters, AssetHubDicleRuntimeDynamicParamsTreasuryParametersKey, AssetHubDicleRuntimeDynamicParamsTreasuryParametersValue, AssetHubDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin, AssetHubDicleRuntimeOriginCaller, AssetHubDicleRuntimeProxyType, AssetHubDicleRuntimeRuntime, AssetHubDicleRuntimeRuntimeError, AssetHubDicleRuntimeRuntimeFreezeReason, AssetHubDicleRuntimeRuntimeHoldReason, AssetHubDicleRuntimeRuntimeParameters, AssetHubDicleRuntimeRuntimeParametersKey, AssetHubDicleRuntimeRuntimeParametersValue, AssetHubDicleRuntimeRuntimeTask, AssetHubDicleRuntimeSessionKeys, AssetHubDicleRuntimeStakingNposCompactSolution24, AssetHubDicleRuntimeTreasuryBurnDestinationAccount, PezpalletProxyProxyDefinitionAssetHubDicleRuntimeProxyType, PezpalletProxyProxyDefinitionDicleRuntimeConstantsProxyProxyType, PezpalletRcMigratorRecoveryPortableActiveRecovery, PezpalletRcMigratorRecoveryPortableRecoveryConfig, PezpalletRcMigratorRecoveryPortableRecoveryFriends, PezpalletRcMigratorRecoveryPortableRecoveryMessage, PezpalletRcMigratorSocietyPortableBid, PezpalletRcMigratorSocietyPortableBidKind, PezpalletRcMigratorSocietyPortableCandidacy, PezpalletRcMigratorSocietyPortableGroupParams, PezpalletRcMigratorSocietyPortableIntakeRecord, PezpalletRcMigratorSocietyPortableMemberRecord, PezpalletRcMigratorSocietyPortablePayoutRecord, PezpalletRcMigratorSocietyPortableSocietyMessage, PezpalletRcMigratorSocietyPortableTally, PezpalletRcMigratorSocietyPortableVote, PezpalletRcMigratorSocietyPortableVouchingStatus, PezpalletRcMigratorSocietySocietyValues, PezpalletRemoteProxyCall, PezpalletRemoteProxyError, PezpalletRemoteProxyRemoteProxyProof, PezpalletReviveEvmApiDebugRpcTypesPrestateTrace, PezpalletReviveEvmApiDebugRpcTypesPrestateTraceInfo, PezpalletReviveEvmApiDebugRpcTypesPrestateTracerConfig, PezpalletReviveStorageAccountInfo, PezpalletReviveStorageAccountType, PezpalletReviveVmCodeInfo, PezspConsensusAuraSr25519AppSr25519Public } from '@pezkuwi/types/lookup';

declare module '@pezkuwi/types/types/registry' {
  interface InterfaceTypes {
    AssetHubDicleRuntimeAhMigrationRcPalletsOrigin: AssetHubDicleRuntimeAhMigrationRcPalletsOrigin;
    AssetHubDicleRuntimeDynamicParamsIssuanceFalloff: AssetHubDicleRuntimeDynamicParamsIssuanceFalloff;
    AssetHubDicleRuntimeDynamicParamsIssuanceIdealStake: AssetHubDicleRuntimeDynamicParamsIssuanceIdealStake;
    AssetHubDicleRuntimeDynamicParamsIssuanceMaxInflation: AssetHubDicleRuntimeDynamicParamsIssuanceMaxInflation;
    AssetHubDicleRuntimeDynamicParamsIssuanceMinInflation: AssetHubDicleRuntimeDynamicParamsIssuanceMinInflation;
    AssetHubDicleRuntimeDynamicParamsIssuanceParameters: AssetHubDicleRuntimeDynamicParamsIssuanceParameters;
    AssetHubDicleRuntimeDynamicParamsIssuanceParametersKey: AssetHubDicleRuntimeDynamicParamsIssuanceParametersKey;
    AssetHubDicleRuntimeDynamicParamsIssuanceParametersValue: AssetHubDicleRuntimeDynamicParamsIssuanceParametersValue;
    AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnIdleWeight: AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnIdleWeight;
    AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnInitWeight: AssetHubDicleRuntimeDynamicParamsMessageQueueMaxOnInitWeight;
    AssetHubDicleRuntimeDynamicParamsMessageQueueParameters: AssetHubDicleRuntimeDynamicParamsMessageQueueParameters;
    AssetHubDicleRuntimeDynamicParamsMessageQueueParametersKey: AssetHubDicleRuntimeDynamicParamsMessageQueueParametersKey;
    AssetHubDicleRuntimeDynamicParamsMessageQueueParametersValue: AssetHubDicleRuntimeDynamicParamsMessageQueueParametersValue;
    AssetHubDicleRuntimeDynamicParamsSchedulerMaxScheduledPerBlock: AssetHubDicleRuntimeDynamicParamsSchedulerMaxScheduledPerBlock;
    AssetHubDicleRuntimeDynamicParamsSchedulerMaximumWeight: AssetHubDicleRuntimeDynamicParamsSchedulerMaximumWeight;
    AssetHubDicleRuntimeDynamicParamsSchedulerParameters: AssetHubDicleRuntimeDynamicParamsSchedulerParameters;
    AssetHubDicleRuntimeDynamicParamsSchedulerParametersKey: AssetHubDicleRuntimeDynamicParamsSchedulerParametersKey;
    AssetHubDicleRuntimeDynamicParamsSchedulerParametersValue: AssetHubDicleRuntimeDynamicParamsSchedulerParametersValue;
    AssetHubDicleRuntimeDynamicParamsStakingElectionMaxElectingVoters: AssetHubDicleRuntimeDynamicParamsStakingElectionMaxElectingVoters;
    AssetHubDicleRuntimeDynamicParamsStakingElectionMaxEraDuration: AssetHubDicleRuntimeDynamicParamsStakingElectionMaxEraDuration;
    AssetHubDicleRuntimeDynamicParamsStakingElectionMaxSignedSubmissions: AssetHubDicleRuntimeDynamicParamsStakingElectionMaxSignedSubmissions;
    AssetHubDicleRuntimeDynamicParamsStakingElectionMinerPages: AssetHubDicleRuntimeDynamicParamsStakingElectionMinerPages;
    AssetHubDicleRuntimeDynamicParamsStakingElectionParameters: AssetHubDicleRuntimeDynamicParamsStakingElectionParameters;
    AssetHubDicleRuntimeDynamicParamsStakingElectionParametersKey: AssetHubDicleRuntimeDynamicParamsStakingElectionParametersKey;
    AssetHubDicleRuntimeDynamicParamsStakingElectionParametersValue: AssetHubDicleRuntimeDynamicParamsStakingElectionParametersValue;
    AssetHubDicleRuntimeDynamicParamsStakingElectionSignedPhase: AssetHubDicleRuntimeDynamicParamsStakingElectionSignedPhase;
    AssetHubDicleRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock: AssetHubDicleRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock;
    AssetHubDicleRuntimeDynamicParamsStakingElectionUnsignedPhase: AssetHubDicleRuntimeDynamicParamsStakingElectionUnsignedPhase;
    AssetHubDicleRuntimeDynamicParamsTreasuryBurnDestination: AssetHubDicleRuntimeDynamicParamsTreasuryBurnDestination;
    AssetHubDicleRuntimeDynamicParamsTreasuryBurnPortion: AssetHubDicleRuntimeDynamicParamsTreasuryBurnPortion;
    AssetHubDicleRuntimeDynamicParamsTreasuryParameters: AssetHubDicleRuntimeDynamicParamsTreasuryParameters;
    AssetHubDicleRuntimeDynamicParamsTreasuryParametersKey: AssetHubDicleRuntimeDynamicParamsTreasuryParametersKey;
    AssetHubDicleRuntimeDynamicParamsTreasuryParametersValue: AssetHubDicleRuntimeDynamicParamsTreasuryParametersValue;
    AssetHubDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin: AssetHubDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin;
    AssetHubDicleRuntimeOriginCaller: AssetHubDicleRuntimeOriginCaller;
    AssetHubDicleRuntimeProxyType: AssetHubDicleRuntimeProxyType;
    AssetHubDicleRuntimeRuntime: AssetHubDicleRuntimeRuntime;
    AssetHubDicleRuntimeRuntimeError: AssetHubDicleRuntimeRuntimeError;
    AssetHubDicleRuntimeRuntimeFreezeReason: AssetHubDicleRuntimeRuntimeFreezeReason;
    AssetHubDicleRuntimeRuntimeHoldReason: AssetHubDicleRuntimeRuntimeHoldReason;
    AssetHubDicleRuntimeRuntimeParameters: AssetHubDicleRuntimeRuntimeParameters;
    AssetHubDicleRuntimeRuntimeParametersKey: AssetHubDicleRuntimeRuntimeParametersKey;
    AssetHubDicleRuntimeRuntimeParametersValue: AssetHubDicleRuntimeRuntimeParametersValue;
    AssetHubDicleRuntimeRuntimeTask: AssetHubDicleRuntimeRuntimeTask;
    AssetHubDicleRuntimeSessionKeys: AssetHubDicleRuntimeSessionKeys;
    AssetHubDicleRuntimeStakingNposCompactSolution24: AssetHubDicleRuntimeStakingNposCompactSolution24;
    AssetHubDicleRuntimeTreasuryBurnDestinationAccount: AssetHubDicleRuntimeTreasuryBurnDestinationAccount;
    PezpalletProxyProxyDefinitionAssetHubDicleRuntimeProxyType: PezpalletProxyProxyDefinitionAssetHubDicleRuntimeProxyType;
    PezpalletProxyProxyDefinitionDicleRuntimeConstantsProxyProxyType: PezpalletProxyProxyDefinitionDicleRuntimeConstantsProxyProxyType;
    PezpalletRcMigratorRecoveryPortableActiveRecovery: PezpalletRcMigratorRecoveryPortableActiveRecovery;
    PezpalletRcMigratorRecoveryPortableRecoveryConfig: PezpalletRcMigratorRecoveryPortableRecoveryConfig;
    PezpalletRcMigratorRecoveryPortableRecoveryFriends: PezpalletRcMigratorRecoveryPortableRecoveryFriends;
    PezpalletRcMigratorRecoveryPortableRecoveryMessage: PezpalletRcMigratorRecoveryPortableRecoveryMessage;
    PezpalletRcMigratorSocietyPortableBid: PezpalletRcMigratorSocietyPortableBid;
    PezpalletRcMigratorSocietyPortableBidKind: PezpalletRcMigratorSocietyPortableBidKind;
    PezpalletRcMigratorSocietyPortableCandidacy: PezpalletRcMigratorSocietyPortableCandidacy;
    PezpalletRcMigratorSocietyPortableGroupParams: PezpalletRcMigratorSocietyPortableGroupParams;
    PezpalletRcMigratorSocietyPortableIntakeRecord: PezpalletRcMigratorSocietyPortableIntakeRecord;
    PezpalletRcMigratorSocietyPortableMemberRecord: PezpalletRcMigratorSocietyPortableMemberRecord;
    PezpalletRcMigratorSocietyPortablePayoutRecord: PezpalletRcMigratorSocietyPortablePayoutRecord;
    PezpalletRcMigratorSocietyPortableSocietyMessage: PezpalletRcMigratorSocietyPortableSocietyMessage;
    PezpalletRcMigratorSocietyPortableTally: PezpalletRcMigratorSocietyPortableTally;
    PezpalletRcMigratorSocietyPortableVote: PezpalletRcMigratorSocietyPortableVote;
    PezpalletRcMigratorSocietyPortableVouchingStatus: PezpalletRcMigratorSocietyPortableVouchingStatus;
    PezpalletRcMigratorSocietySocietyValues: PezpalletRcMigratorSocietySocietyValues;
    PezpalletRemoteProxyCall: PezpalletRemoteProxyCall;
    PezpalletRemoteProxyError: PezpalletRemoteProxyError;
    PezpalletRemoteProxyRemoteProxyProof: PezpalletRemoteProxyRemoteProxyProof;
    PezpalletReviveEvmApiDebugRpcTypesPrestateTrace: PezpalletReviveEvmApiDebugRpcTypesPrestateTrace;
    PezpalletReviveEvmApiDebugRpcTypesPrestateTraceInfo: PezpalletReviveEvmApiDebugRpcTypesPrestateTraceInfo;
    PezpalletReviveEvmApiDebugRpcTypesPrestateTracerConfig: PezpalletReviveEvmApiDebugRpcTypesPrestateTracerConfig;
    PezpalletReviveStorageAccountInfo: PezpalletReviveStorageAccountInfo;
    PezpalletReviveStorageAccountType: PezpalletReviveStorageAccountType;
    PezpalletReviveVmCodeInfo: PezpalletReviveVmCodeInfo;
    PezspConsensusAuraSr25519AppSr25519Public: PezspConsensusAuraSr25519AppSr25519Public;
  } // InterfaceTypes
} // declare module
