// Auto-generated via `yarn polkadot-types-from-defs`, do not edit
/* eslint-disable */

// import type lookup before we augment - in some environments
// this is required to allow for ambient/previous definitions
import '@pezkuwi/types/types/registry';

import type { DicleRuntimeConstantsProxyProxyType, PezpalletRcMigratorRecoveryRecoveryStage, PezpalletRcMigratorSocietySocietyStage, PezpalletRecoveryDepositKind, StagingDicleRuntimeBurnDestinationAccount, StagingDicleRuntimeDynamicParamsInflationFalloff, StagingDicleRuntimeDynamicParamsInflationIdealStake, StagingDicleRuntimeDynamicParamsInflationMaxInflation, StagingDicleRuntimeDynamicParamsInflationMinInflation, StagingDicleRuntimeDynamicParamsInflationParameters, StagingDicleRuntimeDynamicParamsInflationParametersKey, StagingDicleRuntimeDynamicParamsInflationParametersValue, StagingDicleRuntimeDynamicParamsInflationUseAuctionSlots, StagingDicleRuntimeDynamicParamsTreasuryBurnDestination, StagingDicleRuntimeDynamicParamsTreasuryBurnPortion, StagingDicleRuntimeDynamicParamsTreasuryParameters, StagingDicleRuntimeDynamicParamsTreasuryParametersKey, StagingDicleRuntimeDynamicParamsTreasuryParametersValue, StagingDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin, StagingDicleRuntimeNposCompactSolution24, StagingDicleRuntimeOriginCaller, StagingDicleRuntimeRuntime, StagingDicleRuntimeRuntimeError, StagingDicleRuntimeRuntimeFreezeReason, StagingDicleRuntimeRuntimeHoldReason, StagingDicleRuntimeRuntimeParameters, StagingDicleRuntimeRuntimeParametersKey, StagingDicleRuntimeRuntimeParametersValue, StagingDicleRuntimeSessionKeys } from '@pezkuwi/types/lookup';

declare module '@pezkuwi/types/types/registry' {
  interface InterfaceTypes {
    DicleRuntimeConstantsProxyProxyType: DicleRuntimeConstantsProxyProxyType;
    PezpalletRcMigratorRecoveryRecoveryStage: PezpalletRcMigratorRecoveryRecoveryStage;
    PezpalletRcMigratorSocietySocietyStage: PezpalletRcMigratorSocietySocietyStage;
    PezpalletRecoveryDepositKind: PezpalletRecoveryDepositKind;
    StagingDicleRuntimeBurnDestinationAccount: StagingDicleRuntimeBurnDestinationAccount;
    StagingDicleRuntimeDynamicParamsInflationFalloff: StagingDicleRuntimeDynamicParamsInflationFalloff;
    StagingDicleRuntimeDynamicParamsInflationIdealStake: StagingDicleRuntimeDynamicParamsInflationIdealStake;
    StagingDicleRuntimeDynamicParamsInflationMaxInflation: StagingDicleRuntimeDynamicParamsInflationMaxInflation;
    StagingDicleRuntimeDynamicParamsInflationMinInflation: StagingDicleRuntimeDynamicParamsInflationMinInflation;
    StagingDicleRuntimeDynamicParamsInflationParameters: StagingDicleRuntimeDynamicParamsInflationParameters;
    StagingDicleRuntimeDynamicParamsInflationParametersKey: StagingDicleRuntimeDynamicParamsInflationParametersKey;
    StagingDicleRuntimeDynamicParamsInflationParametersValue: StagingDicleRuntimeDynamicParamsInflationParametersValue;
    StagingDicleRuntimeDynamicParamsInflationUseAuctionSlots: StagingDicleRuntimeDynamicParamsInflationUseAuctionSlots;
    StagingDicleRuntimeDynamicParamsTreasuryBurnDestination: StagingDicleRuntimeDynamicParamsTreasuryBurnDestination;
    StagingDicleRuntimeDynamicParamsTreasuryBurnPortion: StagingDicleRuntimeDynamicParamsTreasuryBurnPortion;
    StagingDicleRuntimeDynamicParamsTreasuryParameters: StagingDicleRuntimeDynamicParamsTreasuryParameters;
    StagingDicleRuntimeDynamicParamsTreasuryParametersKey: StagingDicleRuntimeDynamicParamsTreasuryParametersKey;
    StagingDicleRuntimeDynamicParamsTreasuryParametersValue: StagingDicleRuntimeDynamicParamsTreasuryParametersValue;
    StagingDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin: StagingDicleRuntimeGovernanceOriginsPezpalletCustomOriginsOrigin;
    StagingDicleRuntimeNposCompactSolution24: StagingDicleRuntimeNposCompactSolution24;
    StagingDicleRuntimeOriginCaller: StagingDicleRuntimeOriginCaller;
    StagingDicleRuntimeRuntime: StagingDicleRuntimeRuntime;
    StagingDicleRuntimeRuntimeError: StagingDicleRuntimeRuntimeError;
    StagingDicleRuntimeRuntimeFreezeReason: StagingDicleRuntimeRuntimeFreezeReason;
    StagingDicleRuntimeRuntimeHoldReason: StagingDicleRuntimeRuntimeHoldReason;
    StagingDicleRuntimeRuntimeParameters: StagingDicleRuntimeRuntimeParameters;
    StagingDicleRuntimeRuntimeParametersKey: StagingDicleRuntimeRuntimeParametersKey;
    StagingDicleRuntimeRuntimeParametersValue: StagingDicleRuntimeRuntimeParametersValue;
    StagingDicleRuntimeSessionKeys: StagingDicleRuntimeSessionKeys;
  } // InterfaceTypes
} // declare module
