// Copyright 2017-2026 @pezkuwi/api authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as deriveInfo } from '@pezkuwi/api-derive/packageInfo';
import { packageInfo as coreInfo } from '@pezkuwi/rpc-core/packageInfo';
import { packageInfo as providerInfo } from '@pezkuwi/rpc-provider/packageInfo';
import { packageInfo as typesInfo } from '@pezkuwi/types/packageInfo';
import { packageInfo as knownInfo } from '@pezkuwi/types-known/packageInfo';
import { detectPackage } from '@pezkuwi/util';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [coreInfo, deriveInfo, knownInfo, providerInfo, typesInfo]);
